bar:
  height: 26
  location: top
  background: 1e1e2eff
  foreground: cdd6f4ff
  left-spacing: 12
  right-spacing: 8

  left:
    - network:
        content:
          map:
            conditions:
              type == ether || type == wlan:
                map:
                  default:
                    string: {text: "     {ssid}", on-click: networkmanager_dmenu}
                  conditions:
                    ipv4 == "":
                      string: {text: ""}
  right:
    - niri-language:
        content:
            string: {text: "{language} "}
    - backlight:
        name: intel_backlight
        content:
          string: {text: "{percent}% "}
    - pulse:
        anchors:
          volume: &volume
            conditions:
              sink_muted: {string: {text: "0% 🔊", foreground: ff0000ff, right-margin: 5}}
              ~muted: {string: {text: "{sink_percent}% 🔊", right-margin: 10, on-click: pavucontrol}}
        content:
          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          icon == "audio-headset-bluetooth":
                            string: {text: "🎧 "}
                    type == "source":
                      - string: {text: "🎙 "}
              - map:
                  <<: *volume
    - label:
        content:
          string: {text: "", on-click: "sh /home/nik/power.sh", right-margin: 15}
  center: 
    - clock:
        content:
          - string: {text: "{date}", right-margin: 5}
          - string: {text: "{time}"}
